#:schema node_modules/wrangler/config-schema.json
name = "cure-pocket-frontend"
compatibility_date = "2024-11-24"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"