[package]
name = "cure_pocket"
edition = "2024.beta"
# authors = ["bubuBUTASAN(bububutasan00@gmail.com), SHIZUKU"]

[dependencies]

[addresses]
cure_pocket_contract = "0x0"

[dev-dependencies]


[dev-addresses]


